export const UiIcons = {
  metadata: '⭐',
  createMetadata: '🌟',
  add: '➕',
  edit: '✏️',
  delete: '🗑️',
  fileBrowser: '🗂️',
  folder: '📁',
  settings: '⚙️',
  home: '🏠',
  image: '🖼️',
  audio: '🎵',
  video: '🎬',
  doc: '📄',
  refresh: '🔄',
}
